[theme]
primaryColor="#FF4B4B"
backgroundColor="#F0F2F6"
secondaryBackgroundColor="#E6E9EF"
textColor="#1E1E1E"
font="sans serif"

[server]
enableXsrfProtection=true
enableCORS=false
enableWebsocketCompression=true

[browser]
gatherUsageStats=false 